// <auto-generated />
using System;
using ExploreParks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExploreParks.Migrations
{
    [DbContext(typeof(ExploreParksDbContext))]
    partial class ExploreParksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExploreParks.Models.ContinentModel", b =>
                {
                    b.Property<Guid>("ContinentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContinentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentId");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("ExploreParks.Models.CountryModel", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContinentModelContinentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.HasIndex("ContinentModelContinentId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ExploreParks.Models.ParkModel", b =>
                {
                    b.Property<Guid>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CountryModelCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NearestCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkEstablished")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParkId");

                    b.HasIndex("CountryModelCountryId");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("ExploreParks.Models.getDescription", b =>
                {
                    b.Property<Guid>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NearestCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkLatitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkLongitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParkId");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("ExploreParks.Models.CountryModel", b =>
                {
                    b.HasOne("ExploreParks.Models.ContinentModel", null)
                        .WithMany("Countries")
                        .HasForeignKey("ContinentModelContinentId");
                });

            modelBuilder.Entity("ExploreParks.Models.ParkModel", b =>
                {
                    b.HasOne("ExploreParks.Models.CountryModel", null)
                        .WithMany("Parks")
                        .HasForeignKey("CountryModelCountryId");
                });

            modelBuilder.Entity("ExploreParks.Models.ContinentModel", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("ExploreParks.Models.CountryModel", b =>
                {
                    b.Navigation("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
