// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using scrapper.Data;

#nullable disable

namespace scrapper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231126185904_EmptyMigration")]
    partial class EmptyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("scrapper.Models.parkModels", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectionsInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectionsUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntranceFees")
                        .HasColumnType("TEXT");

                    b.Property<string>("Established")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NearestCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("parkModels");
                });

            modelBuilder.Entity("scrapper.Models.parkName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Established")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("parkName");
                });
#pragma warning restore 612, 618
        }
    }
}
